# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 581)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1215, 581))
        MainWindow.setMaximumSize(QtCore.QSize(1215, 581))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1173, 543))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 223))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 54))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scan_label = QtWidgets.QLabel(self.groupBox)
        self.scan_label.setMinimumSize(QtCore.QSize(31, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.scan_label.setFont(font)
        self.scan_label.setAlignment(QtCore.Qt.AlignCenter)
        self.scan_label.setObjectName("scan_label")
        self.gridLayout_6.addWidget(self.scan_label, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_sql = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_sql.setMaximumSize(QtCore.QSize(200, 55))
        self.btn_sql.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sql.setObjectName("btn_sql")
        self.gridLayout_5.addWidget(self.btn_sql, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_theme = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_theme.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_theme.setIconSize(QtCore.QSize(25, 25))
        self.checkBox_theme.setObjectName("checkBox_theme")
        self.gridLayout_7.addWidget(self.checkBox_theme, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 59))
        self.groupBox_4.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.spinBox_mute = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_mute.setEnabled(False)
        self.spinBox_mute.setMinimumSize(QtCore.QSize(0, 17))
        self.spinBox_mute.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_mute.setMinimum(1)
        self.spinBox_mute.setMaximum(30)
        self.spinBox_mute.setProperty("value", 1)
        self.spinBox_mute.setObjectName("spinBox_mute")
        self.gridLayout_3.addWidget(self.spinBox_mute, 1, 0, 1, 1)
        self.checkBox_pause = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_pause.setObjectName("checkBox_pause")
        self.gridLayout_3.addWidget(self.checkBox_pause, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox.setMinimumSize(QtCore.QSize(75, 29))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.play_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.play_btn.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(14)
        self.play_btn.setFont(font)
        self.play_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_btn.setStyleSheet("")
        self.play_btn.setAutoDefault(False)
        self.play_btn.setDefault(False)
        self.play_btn.setFlat(False)
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout_3.addWidget(self.play_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.date_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.date_label.setFont(font)
        self.date_label.setFrameShape(QtWidgets.QFrame.Box)
        self.date_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.date_label.setText("")
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_4.addWidget(self.widget1)
        self.verticalLayout_6.addWidget(self.widget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 8, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(650, 200))
        self.label.setMaximumSize(QtCore.QSize(16777215, 215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stop_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy)
        self.stop_btn.setMinimumSize(QtCore.QSize(650, 0))
        self.stop_btn.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stop_btn.setFont(font)
        self.stop_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_btn.setToolTip("")
        self.stop_btn.setToolTipDuration(2)
        self.stop_btn.setStatusTip("")
        self.stop_btn.setWhatsThis("")
        self.stop_btn.setAccessibleName("")
        self.stop_btn.setAccessibleDescription("")
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout_3.addWidget(self.stop_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_img = QtWidgets.QLabel(self.layoutWidget)
        self.label_img.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.label_img.setFont(font)
        self.label_img.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_img.setStyleSheet("")
        self.label_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.verticalLayout.addWidget(self.label_img)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Alert"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection Status"))
        self.scan_label.setText(_translate("MainWindow", "No Action"))
        self.groupBox_3.setTitle(_translate("MainWindow", "SQL"))
        self.btn_sql.setText(_translate("MainWindow", "Open SQL Data"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Theme"))
        self.checkBox_theme.setText(_translate("MainWindow", "Dark Style"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Pause Duration"))
        self.label_3.setText(_translate("MainWindow", "Minutes"))
        self.checkBox_pause.setText(_translate("MainWindow", "Enable"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Alert Sound"))
        self.play_btn.setText(_translate("MainWindow", "w"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Date/Time of last detection:"))
        self.label.setText(_translate("MainWindow", "Nothing Yet"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.label_2.setText(_translate("MainWindow", "Live Video Streaming"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

