# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 689)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_img = QtWidgets.QLabel(self.tab)
        self.label_img.setMinimumSize(QtCore.QSize(640, 480))
        self.label_img.setMaximumSize(QtCore.QSize(640, 480))
        self.label_img.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.verticalLayout_2.addWidget(self.label_img)
        self.label_server = QtWidgets.QLabel(self.tab)
        self.label_server.setText("")
        self.label_server.setObjectName("label_server")
        self.verticalLayout_2.addWidget(self.label_server)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_play = QtWidgets.QPushButton(self.tab)
        self.btn_play.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play.setObjectName("btn_play")
        self.verticalLayout.addWidget(self.btn_play)
        self.btn_server = QtWidgets.QPushButton(self.tab)
        self.btn_server.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_server.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_server.setObjectName("btn_server")
        self.verticalLayout.addWidget(self.btn_server)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_4.addWidget(self.lineEdit_username)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_11.addWidget(self.lineEdit_password)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.btn_apply_hash = QtWidgets.QPushButton(self.frame_2)
        self.btn_apply_hash.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_apply_hash.setFont(font)
        self.btn_apply_hash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_apply_hash.setObjectName("btn_apply_hash")
        self.verticalLayout_12.addWidget(self.btn_apply_hash)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_hashed_username = QtWidgets.QLabel(self.groupBox_2)
        self.label_hashed_username.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_hashed_username.setFont(font)
        self.label_hashed_username.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_hashed_username.setText("")
        self.label_hashed_username.setObjectName("label_hashed_username")
        self.gridLayout_3.addWidget(self.label_hashed_username, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_hashed_password = QtWidgets.QLabel(self.groupBox_3)
        self.label_hashed_password.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_hashed_password.setFont(font)
        self.label_hashed_password.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_hashed_password.setText("")
        self.label_hashed_password.setObjectName("label_hashed_password")
        self.gridLayout_4.addWidget(self.label_hashed_password, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.btn_export_hash = QtWidgets.QPushButton(self.frame_2)
        self.btn_export_hash.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_export_hash.setFont(font)
        self.btn_export_hash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_export_hash.setObjectName("btn_export_hash")
        self.verticalLayout_16.addWidget(self.btn_export_hash)
        self.gridLayout_13.addLayout(self.verticalLayout_16, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 148, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 3, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_play.setText(_translate("MainWindow", "Open Camera"))
        self.btn_server.setText(_translate("MainWindow", "Run Server"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Camera"))
        self.label.setText(_translate("MainWindow", "UserName"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.btn_apply_hash.setText(_translate("MainWindow", "Apply Hash Function"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hashed Username"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Hashed Password"))
        self.btn_export_hash.setText(_translate("MainWindow", "Export NamePass file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

